# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: customer.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "customer.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0e\x63ustomer.proto\x12\x08\x63ustomer"T\n\x07\x41\x64\x64ress\x12\x0e\n\x06street\x18\x01 \x01(\t\x12\x0c\n\x04\x63ity\x18\x02 \x01(\t\x12\r\n\x05state\x18\x03 \x01(\t\x12\x0b\n\x03zip\x18\x04 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x05 \x01(\t"\x85\x01\n\x08\x43ustomer\x12\x12\n\ncustomerid\x18\x01 \x01(\t\x12\x11\n\tfirstname\x18\x02 \x01(\t\x12\x10\n\x08lastname\x18\x03 \x01(\t\x12\r\n\x05\x65mail\x18\x04 \x01(\t\x12\r\n\x05phone\x18\x05 \x01(\t\x12"\n\x07\x61\x64\x64ress\x18\x06 \x01(\x0b\x32\x11.customer.Address"=\n\x15\x43reateCustomerRequest\x12$\n\x08\x63ustomer\x18\x01 \x01(\x0b\x32\x12.customer.Customer"5\n\x16\x43reateCustomerResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t",\n\x16GetCustomerByIdRequest\x12\x12\n\ncustomerid\x18\x01 \x01(\t"\\\n\x17GetCustomerByIdResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12$\n\x08\x63ustomer\x18\x03 \x01(\x0b\x32\x12.customer.Customer"Q\n\x15UpdateCustomerRequest\x12\x12\n\ncustomerid\x18\x01 \x01(\t\x12$\n\x08\x63ustomer\x18\x02 \x01(\x0b\x32\x12.customer.Customer"5\n\x16UpdateCustomerResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t"+\n\x15\x44\x65leteCustomerRequest\x12\x12\n\ncustomerid\x18\x01 \x01(\t"5\n\x16\x44\x65leteCustomerResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xe8\x02\n\x0f\x43ustomerService\x12S\n\x0e\x43reateCustomer\x12\x1f.customer.CreateCustomerRequest\x1a .customer.CreateCustomerResponse\x12V\n\x0fGetCustomerById\x12 .customer.GetCustomerByIdRequest\x1a!.customer.GetCustomerByIdResponse\x12S\n\x0eUpdateCustomer\x12\x1f.customer.UpdateCustomerRequest\x1a .customer.UpdateCustomerResponse\x12S\n\x0e\x44\x65leteCustomer\x12\x1f.customer.DeleteCustomerRequest\x1a .customer.DeleteCustomerResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "customer_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_ADDRESS"]._serialized_start = 28
    _globals["_ADDRESS"]._serialized_end = 112
    _globals["_CUSTOMER"]._serialized_start = 115
    _globals["_CUSTOMER"]._serialized_end = 248
    _globals["_CREATECUSTOMERREQUEST"]._serialized_start = 250
    _globals["_CREATECUSTOMERREQUEST"]._serialized_end = 311
    _globals["_CREATECUSTOMERRESPONSE"]._serialized_start = 313
    _globals["_CREATECUSTOMERRESPONSE"]._serialized_end = 366
    _globals["_GETCUSTOMERBYIDREQUEST"]._serialized_start = 368
    _globals["_GETCUSTOMERBYIDREQUEST"]._serialized_end = 412
    _globals["_GETCUSTOMERBYIDRESPONSE"]._serialized_start = 414
    _globals["_GETCUSTOMERBYIDRESPONSE"]._serialized_end = 506
    _globals["_UPDATECUSTOMERREQUEST"]._serialized_start = 508
    _globals["_UPDATECUSTOMERREQUEST"]._serialized_end = 589
    _globals["_UPDATECUSTOMERRESPONSE"]._serialized_start = 591
    _globals["_UPDATECUSTOMERRESPONSE"]._serialized_end = 644
    _globals["_DELETECUSTOMERREQUEST"]._serialized_start = 646
    _globals["_DELETECUSTOMERREQUEST"]._serialized_end = 689
    _globals["_DELETECUSTOMERRESPONSE"]._serialized_start = 691
    _globals["_DELETECUSTOMERRESPONSE"]._serialized_end = 744
    _globals["_CUSTOMERSERVICE"]._serialized_start = 747
    _globals["_CUSTOMERSERVICE"]._serialized_end = 1107
# @@protoc_insertion_point(module_scope)
