# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import warnings  # noqa: F401 (Ignore "unused import" for this line only)

from . import customer_pb2 as customer__pb2

GRPC_GENERATED_VERSION = "1.76.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in customer_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class CustomerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateCustomer = channel.unary_unary(
            "/customer.CustomerService/CreateCustomer",
            request_serializer=customer__pb2.CreateCustomerRequest.SerializeToString,
            response_deserializer=customer__pb2.CreateCustomerResponse.FromString,
            _registered_method=True,
        )
        self.GetCustomerById = channel.unary_unary(
            "/customer.CustomerService/GetCustomerById",
            request_serializer=customer__pb2.GetCustomerByIdRequest.SerializeToString,
            response_deserializer=customer__pb2.GetCustomerByIdResponse.FromString,
            _registered_method=True,
        )
        self.UpdateCustomer = channel.unary_unary(
            "/customer.CustomerService/UpdateCustomer",
            request_serializer=customer__pb2.UpdateCustomerRequest.SerializeToString,
            response_deserializer=customer__pb2.UpdateCustomerResponse.FromString,
            _registered_method=True,
        )
        self.DeleteCustomer = channel.unary_unary(
            "/customer.CustomerService/DeleteCustomer",
            request_serializer=customer__pb2.DeleteCustomerRequest.SerializeToString,
            response_deserializer=customer__pb2.DeleteCustomerResponse.FromString,
            _registered_method=True,
        )


class CustomerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateCustomer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetCustomerById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def UpdateCustomer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DeleteCustomer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_CustomerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "CreateCustomer": grpc.unary_unary_rpc_method_handler(
            servicer.CreateCustomer,
            request_deserializer=customer__pb2.CreateCustomerRequest.FromString,
            response_serializer=customer__pb2.CreateCustomerResponse.SerializeToString,
        ),
        "GetCustomerById": grpc.unary_unary_rpc_method_handler(
            servicer.GetCustomerById,
            request_deserializer=customer__pb2.GetCustomerByIdRequest.FromString,
            response_serializer=customer__pb2.GetCustomerByIdResponse.SerializeToString,
        ),
        "UpdateCustomer": grpc.unary_unary_rpc_method_handler(
            servicer.UpdateCustomer,
            request_deserializer=customer__pb2.UpdateCustomerRequest.FromString,
            response_serializer=customer__pb2.UpdateCustomerResponse.SerializeToString,
        ),
        "DeleteCustomer": grpc.unary_unary_rpc_method_handler(
            servicer.DeleteCustomer,
            request_deserializer=customer__pb2.DeleteCustomerRequest.FromString,
            response_serializer=customer__pb2.DeleteCustomerResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "customer.CustomerService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "customer.CustomerService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class CustomerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateCustomer(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/customer.CustomerService/CreateCustomer",
            customer__pb2.CreateCustomerRequest.SerializeToString,
            customer__pb2.CreateCustomerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetCustomerById(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/customer.CustomerService/GetCustomerById",
            customer__pb2.GetCustomerByIdRequest.SerializeToString,
            customer__pb2.GetCustomerByIdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def UpdateCustomer(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/customer.CustomerService/UpdateCustomer",
            customer__pb2.UpdateCustomerRequest.SerializeToString,
            customer__pb2.UpdateCustomerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def DeleteCustomer(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/customer.CustomerService/DeleteCustomer",
            customer__pb2.DeleteCustomerRequest.SerializeToString,
            customer__pb2.DeleteCustomerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
